export const data = [
  {
    id: "4",
    name: "SmartLedger",
    category: "webapps",
    link: "https://thierry256-dev.github.io/SmartLedger/",
    github: "https://github.com/Thierry256-dev/SmartLedger.git",
    description:
      "SmartLedger is a React demo web app that helps a user to track his/her finances. It graphically displays income vs expenditure and categorises the expenditure. The app completely depends on localStorage to store and retrive data.",
    coverImage: "/opt/s.webp",
    tech: "React | Tailwindcss",
    screenshots: [
      "/opt/s.webp",
      "/opt/s1.webp",
      "/opt/s2.webp",
      "/opt/s3.webp",
      "/opt/s4.webp",
      "/opt/sm.webp",
    ],
  },
  {
    id: "3",
    name: "BuyMe",
    category: "webapps",
    link: "https://thierry256-dev.github.io/BuyMe/",
    github: "https://github.com/Thierry256-dev/BuyMe.git",
    description:
      "BuyMe is an online shopping demo web app. The app displays product categories and uses Fuse.js to enable a user easily find their desired items. The cart is stored and retrieved from LocalStorage. Checkout and Payment pages are included.",
    coverImage: "/opt/b.webp",
    tech: "HTML | CSS3 | JavaScript",
    screenshots: [
      "/opt/b1.webp",
      "/opt/b2.webp",
      "/opt/b3.webp",
      "/opt/b4.webp",
      "/opt/b5.webp",
      "/opt/b6.webp",
      "/opt/bc1.webp",
      "/opt/bp1.webp",
      "/opt/bs1.webp",
      "/opt/bs2.webp",
      "/opt/bs3.webp",
      "/opt/bs4.webp",
      "/opt/bs5.webp",
      "/opt/bs6.webp",
      "/opt/bcs1.webp",
      "/opt/bps1.webp",
    ],
  },
  {
    id: "2",
    name: "Brew Haven",
    category: "designs",
    link: "https://thierry-brew-haven.netlify.app",
    github: "",
    description:
      "Brew Haven is a one page CoffeeShop website with a modern web design.",
    coverImage: "/opt/c1.webp",
    tech: "HTML | CSS3 | JavaScript",
    screenshots: [
      "/opt/c1.webp",
      "/opt/c2.webp",
      "/opt/c3.webp",
      "/opt/c4.webp",
      "/opt/c5.webp",
      "/opt/c6.webp",
      "/opt/cs1.webp",
      "/opt/cs2.webp",
      "/opt/cs3.webp",
      "/opt/cs4.webp",
      "/opt/cs5.webp",
      "/opt/cs6.webp",
      "/opt/cs7.webp",
      "/opt/cs8.webp",
      "/opt/cs9.webp",
    ],
  },
  {
    id: "1",
    name: "Merryland Hybrid",
    category: "designs",
    link: "https://thierry256-dev.github.io/myprojects/",
    github: "https://github.com/Thierry256-dev/myprojects.git",
    description:
      "Merryland Hybrid is a multi-page school website whose design is inspired from the Merryland Schools,Entebbe.",
    coverImage: "/opt/m.webp",
    tech: "HTML | CSS3 | JavaScript",
    screenshots: [
      "/opt/m1.webp",
      "/opt/m2.webp",
      "/opt/m3.webp",
      "/opt/ma.webp",
      "/opt/mf.webp",
      "/opt/mp1.webp",
      "/opt/mp2.webp",
      "/opt/mg1.webp",
      "/opt/mg2.webp",
      "/opt/mg3.webp",
      "/opt/mg4.webp",
      "/opt/mc.webp",
      "/opt/m4.webp",
    ],
  },
];
