export const educationData = [
  {
    id: "3",
    achievement: "Bachelor of Science  Technology-Physics",
    badge: "/edu/kyu.png",
    instituton: "Kyambogo University",
    duration: "2025-today",
    studyCore: "Applied Physics",
    comment: "I am currently pursuing a Bachelor with a strong focus on;",
    emphasis: [
      "Computational Physics/Programming",
      "Classical Mechanics",
      "Electronics and Instrumentation",
      "Materials Science",
    ],
  },
  {
    id: "2",
    achievement: "UACE-Uganda Advanced Certificate Of Education",
    badge: "/edu/merro.jpg",
    instituton: "Merryland High School, Entebbe",
    duration: "2023-2024",
    studyCore: "PCM/ICT",
    comment: "I completed a science study program with a major focus on;",
    emphasis: [
      "Physics",
      "Mathematics",
      "Chemistry",
      "Information and Communications Technology",
    ],
  },
  {
    id: "1",
    achievement: "UCE-Uganda Certificate of Education",
    badge: "/edu/merro.jpg",
    instituton: "Merryland High School, Entebbe",
    duration: "2018-2022",
    studyCore: "Sciences and Arts",
    comment: "I completed a 4-year compact program covering;",
    emphasis: ["Sciences", "Arts", "VocationalStudies in Foods and Nutrition"],
  },
];

export const techStack = [
  {
    id: "1",
    language: "HTML",
    progress: "100%",
    icon: "html",
    color: "#E34F26",
    comment: "Strong Foundation",
  },
  {
    id: "2",
    language: "CSS",
    progress: "90%",
    icon: "css",
    color: "#1572B6",
    comment: "Solid understanding, still growing",
  },
  {
    id: "3",
    language: "JavaScript",
    progress: "80%",
    icon: "js",
    color: "#F7DF1E",
    comment: "Confident in building real-world projects",
  },
  {
    id: "4",
    language: "ReactJs",
    progress: "65%",
    icon: "rct",
    color: "#61DAFB",
    comment: "Actively learning and practicing",
  },
  {
    id: "5",
    language: "Tailwindcss",
    progress: "85%",
    icon: "tailwind",
    color: "#38BDF8",
    comment: "Comfortable with most features",
  },
  {
    id: "6",
    language: "Git",
    progress: "85%",
    icon: "git",
    color: "#ac2810",
    comment: "Actively practicing",
  },
];
